version: '3.8'
services:
  api-server:
   build: .
   depends_on:
      - redis
   ports:
    - "3000:3000"

  redis:
    image: redis:7.0.11-alpine
    container_name: redis-coder-byte
    ports:
      - 6379:6379
    volumes:
      - .docker/redis/data:/data
    command:
      - /bin/sh
      - -c
      - 'redis-server --save 30 1'
      
  mongodb:
          image: mongo:latest
          container_name: mongodb-coder-byte
          ports:
            - 27017:27017
          volumes:
            - .docker/mongodb/data:/data/db